# Woodpecker CI - Build All TTS Engines (Sequential)
#
# Builds engines one at a time to reduce disk usage.
# Aggressively cleans up after each build to free space.
#
# Required Secrets (set in Woodpecker UI):
#   - github_token: GitHub PAT with packages:write
#   - github_username: Your GitHub username

labels:
  platform: linux/amd64

when:
  - event: push
    branch: main
  - event: manual

steps:
  # Initial cleanup - remove ALL Docker artifacts
  cleanup:
    image: docker:latest
    commands:
      - echo "=== Initial Cleanup ==="
      - docker system prune -af || true
      - docker builder prune -af || true
      - df -h / || true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Build Kokoro (smallest, build first)
  build-kokoro:
    image: docker:latest
    commands:
      - echo "=== Building Kokoro ==="
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker build 
          -t ghcr.io/gbstox/tts-kokoro:latest 
          -t ghcr.io/gbstox/tts-kokoro:${CI_COMMIT_SHA:0:7}
          -f engines/kokoro/Dockerfile .
      - docker push ghcr.io/gbstox/tts-kokoro:latest
      - docker push ghcr.io/gbstox/tts-kokoro:${CI_COMMIT_SHA:0:7}
      - echo "=== Pushed tts-kokoro ==="
      - echo "Cleaning up Kokoro image and cache..."
      - docker rmi ghcr.io/gbstox/tts-kokoro:latest ghcr.io/gbstox/tts-kokoro:${CI_COMMIT_SHA:0:7} || true
      - docker builder prune -af || true
      - df -h / || true
    secrets:
      - github_token
      - github_username
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - cleanup

  # Build CosyVoice (after Kokoro)
  build-cosyvoice:
    image: docker:latest
    commands:
      - echo "=== Building CosyVoice ==="
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker build 
          -t ghcr.io/gbstox/tts-cosyvoice:latest 
          -t ghcr.io/gbstox/tts-cosyvoice:${CI_COMMIT_SHA:0:7}
          -f engines/cosyvoice/Dockerfile .
      - docker push ghcr.io/gbstox/tts-cosyvoice:latest
      - docker push ghcr.io/gbstox/tts-cosyvoice:${CI_COMMIT_SHA:0:7}
      - echo "=== Pushed tts-cosyvoice ==="
      - echo "Cleaning up CosyVoice image and cache..."
      - docker rmi ghcr.io/gbstox/tts-cosyvoice:latest ghcr.io/gbstox/tts-cosyvoice:${CI_COMMIT_SHA:0:7} || true
      - docker builder prune -af || true
      - df -h / || true
    secrets:
      - github_token
      - github_username
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - build-kokoro

  # Build Fish Speech (after CosyVoice)
  build-fishspeech:
    image: docker:latest
    commands:
      - echo "=== Building Fish Speech ==="
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker build 
          -t ghcr.io/gbstox/tts-fishspeech:latest 
          -t ghcr.io/gbstox/tts-fishspeech:${CI_COMMIT_SHA:0:7}
          -f engines/fishspeech/Dockerfile .
      - docker push ghcr.io/gbstox/tts-fishspeech:latest
      - docker push ghcr.io/gbstox/tts-fishspeech:${CI_COMMIT_SHA:0:7}
      - echo "=== Pushed tts-fishspeech ==="
      - echo "Cleaning up Fish Speech image and cache..."
      - docker rmi ghcr.io/gbstox/tts-fishspeech:latest ghcr.io/gbstox/tts-fishspeech:${CI_COMMIT_SHA:0:7} || true
      - docker builder prune -af || true
      - df -h / || true
    secrets:
      - github_token
      - github_username
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - build-cosyvoice

  # Build Qwen3-TTS (after Fish Speech)
  build-qwen3tts:
    image: docker:latest
    commands:
      - echo "=== Building Qwen3-TTS ==="
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker build 
          -t ghcr.io/gbstox/tts-qwen3tts:latest 
          -t ghcr.io/gbstox/tts-qwen3tts:${CI_COMMIT_SHA:0:7}
          -f engines/qwen3tts/Dockerfile .
      - docker push ghcr.io/gbstox/tts-qwen3tts:latest
      - docker push ghcr.io/gbstox/tts-qwen3tts:${CI_COMMIT_SHA:0:7}
      - echo "=== Pushed tts-qwen3tts ==="
      - echo "Cleaning up Qwen3-TTS image and cache..."
      - docker rmi ghcr.io/gbstox/tts-qwen3tts:latest ghcr.io/gbstox/tts-qwen3tts:${CI_COMMIT_SHA:0:7} || true
      - docker builder prune -af || true
      - df -h / || true
    secrets:
      - github_token
      - github_username
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - build-fishspeech

  # Summary
  summary:
    image: alpine
    commands:
      - echo "=== Build Complete ==="
      - echo "Images pushed to ghcr.io/gbstox/:"
      - echo "  - tts-kokoro:latest"
      - echo "  - tts-cosyvoice:latest"
      - echo "  - tts-fishspeech:latest"
      - echo "  - tts-qwen3tts:latest"
    depends_on:
      - build-qwen3tts
# Trigger build 20260126-000527
# Retry 1769396068
