# Woodpecker CI - Build All TTS Engines (Sequential)
#
# Builds engines one at a time to reduce disk usage.
# Cleans up after each build to free space.
#
# Required Secrets (set in Woodpecker UI):
#   - github_token: GitHub PAT with packages:write
#   - github_username: Your GitHub username

labels:
  platform: linux/amd64

when:
  - event: push
    branch: main
  - event: manual

steps:
  # Initial cleanup
  cleanup:
    image: docker:latest
    commands:
      - echo "Cleaning up old Docker artifacts..."
      - docker system prune -f || true
      - docker builder prune -f || true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Build Kokoro (smallest, build first)
  build-kokoro:
    image: docker:latest
    commands:
      - echo "=== Building Kokoro ==="
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker build 
          -t ghcr.io/gbstox/tts-kokoro:latest 
          -t ghcr.io/gbstox/tts-kokoro:${CI_COMMIT_SHA:0:7}
          -f engines/kokoro/Dockerfile .
      - docker push ghcr.io/gbstox/tts-kokoro:latest
      - docker push ghcr.io/gbstox/tts-kokoro:${CI_COMMIT_SHA:0:7}
      - echo "=== Pushed tts-kokoro ==="
      - docker builder prune -f || true
    secrets:
      - github_token
      - github_username
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - cleanup

  # Build CosyVoice (after Kokoro)
  build-cosyvoice:
    image: docker:latest
    commands:
      - echo "=== Building CosyVoice ==="
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker build 
          -t ghcr.io/gbstox/tts-cosyvoice:latest 
          -t ghcr.io/gbstox/tts-cosyvoice:${CI_COMMIT_SHA:0:7}
          -f engines/cosyvoice/Dockerfile .
      - docker push ghcr.io/gbstox/tts-cosyvoice:latest
      - docker push ghcr.io/gbstox/tts-cosyvoice:${CI_COMMIT_SHA:0:7}
      - echo "=== Pushed tts-cosyvoice ==="
      - docker builder prune -f || true
    secrets:
      - github_token
      - github_username
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - build-kokoro

  # Build Fish Speech (after CosyVoice)
  build-fishspeech:
    image: docker:latest
    commands:
      - echo "=== Building Fish Speech ==="
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker build 
          -t ghcr.io/gbstox/tts-fishspeech:latest 
          -t ghcr.io/gbstox/tts-fishspeech:${CI_COMMIT_SHA:0:7}
          -f engines/fishspeech/Dockerfile .
      - docker push ghcr.io/gbstox/tts-fishspeech:latest
      - docker push ghcr.io/gbstox/tts-fishspeech:${CI_COMMIT_SHA:0:7}
      - echo "=== Pushed tts-fishspeech ==="
      - docker builder prune -f || true
    secrets:
      - github_token
      - github_username
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - build-cosyvoice

  # Summary
  summary:
    image: alpine
    commands:
      - echo "=== Build Complete ==="
      - echo "Images pushed to ghcr.io/gbstox/:"
      - echo "  - tts-kokoro:latest"
      - echo "  - tts-cosyvoice:latest"
      - echo "  - tts-fishspeech:latest"
    depends_on:
      - build-fishspeech
