# Woodpecker CI - Build Qwen3-TTS Only
#
# Standalone build for Qwen3-TTS to avoid timeout issues.

labels:
  platform: linux/amd64

when:
  - event: manual

steps:
  # Initial cleanup
  cleanup:
    image: docker:latest
    commands:
      - echo "=== Initial Cleanup ==="
      - docker system prune -af || true
      - docker builder prune -af || true
      - df -h / || true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Build Qwen3-TTS
  build-qwen3tts:
    image: docker:latest
    commands:
      - echo "=== Building Qwen3-TTS ==="
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker build 
          -t ghcr.io/gbstox/tts-qwen3tts:latest 
          -t ghcr.io/gbstox/tts-qwen3tts:${CI_COMMIT_SHA:0:7}
          -f engines/qwen3tts/Dockerfile .
      - echo "=== Build complete, starting push ==="
      - docker push ghcr.io/gbstox/tts-qwen3tts:latest
      - echo "=== Pushed :latest ==="
      - docker push ghcr.io/gbstox/tts-qwen3tts:${CI_COMMIT_SHA:0:7}
      - echo "=== Pushed commit tag ==="
      - echo "=== Successfully pushed tts-qwen3tts ==="
    secrets:
      - github_token
      - github_username
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - cleanup
