# Woodpecker CI - Qwen3-TTS Only Build

when:
  - event: manual

steps:
  build-and-push:
    image: docker:latest
    commands:
      - echo "=== Starting Qwen3-TTS Build ==="
      - docker system prune -af || true
      - docker builder prune -af || true
      - df -h /
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker build -t ghcr.io/gbstox/tts-qwen3tts:latest -f engines/qwen3tts/Dockerfile .
      - echo "=== Build complete, pushing... ==="
      - docker push ghcr.io/gbstox/tts-qwen3tts:latest
      - echo "=== Successfully pushed tts-qwen3tts ==="
    secrets:
      - github_token
      - github_username
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
